"""Tests for the --additive CLI flags on ``lia-graph-artifacts`` (Phase 6)."""

from __future__ import annotations

import io
import json
from contextlib import redirect_stdout

import pytest

from lia_graph.ingest import main, parser


# (a) parser exposes the four new flags.
def test_parser_exposes_additive_flags() -> None:
    p = parser()
    help_text = p.format_help()
    assert "--additive" in help_text
    assert "--delta-id" in help_text
    assert "--dry-run-delta" in help_text
    assert "--strict-parity" in help_text


# (b) parsing --additive + flags sets expected fields.
def test_parser_captures_additive_flag_values() -> None:
    p = parser()
    args = p.parse_args(
        [
            "--additive",
            "--delta-id",
            "delta_fixture_test",
            "--dry-run-delta",
            "--strict-parity",
            "--supabase-sink",
        ]
    )
    assert args.additive is True
    assert args.delta_id == "delta_fixture_test"
    assert args.dry_run_delta is True
    assert args.strict_parity is True
    assert args.supabase_sink is True


# (c) --additive without --supabase-sink errors with a clear message.
def test_additive_without_supabase_sink_errors() -> None:
    buf = io.StringIO()
    with redirect_stdout(buf):
        rc = main(
            [
                "--additive",
                "--no-supabase-sink",
                "--allow-non-local-env",
                "--json",
            ]
        )
    assert rc == 2
    payload = json.loads(buf.getvalue())
    assert payload["ok"] is False
    assert payload["error"] == "additive_requires_supabase"


# (d) --strict-parity flag defaults to False.
def test_strict_parity_defaults_false() -> None:
    p = parser()
    args = p.parse_args(["--additive"])
    assert args.strict_parity is False


# (e) --dry-run-delta flag defaults to False.
def test_dry_run_delta_defaults_false() -> None:
    p = parser()
    args = p.parse_args(["--additive"])
    assert args.dry_run_delta is False


# (f) --delta-id flag defaults to None (auto-generated by the runtime).
def test_delta_id_defaults_none() -> None:
    p = parser()
    args = p.parse_args(["--additive"])
    assert args.delta_id is None


# (g) env-matrix version stays in sync across the 5 mirror surfaces.
# Source of truth: docs/guide/orchestration.md `### Current version:` line
# (per CLAUDE.md — code/docs reconcile to orchestration.md, never the other
# way around). Test derives the expected version from that anchor so a
# version bump only requires updating orchestration.md + propagating to the
# other 4 mirrors; no manual test edit needed.
def test_env_matrix_version_landed_across_mirrors() -> None:
    import re
    from pathlib import Path

    repo_root = Path(__file__).resolve().parent.parent
    orchestration_path = repo_root / "docs" / "guide" / "orchestration.md"
    assert orchestration_path.exists(), f"missing source-of-truth file: {orchestration_path}"

    orchestration_text = orchestration_path.read_text(encoding="utf-8")
    match = re.search(
        r"^### Current version:\s*`(v\d{4}-\d{2}-\d{2}-[a-z0-9-]+)`",
        orchestration_text,
        re.MULTILINE,
    )
    assert match, (
        "Could not locate `### Current version: `<version>`` anchor in "
        f"{orchestration_path}. Update the regex if the heading shape changed."
    )
    expected_version = match.group(1)

    mirror_files = [
        repo_root / "AGENTS.md",
        repo_root / "docs" / "guide" / "env_guide.md",
        repo_root / "CLAUDE.md",
        repo_root / "frontend" / "src" / "features" / "orchestration" / "orchestrationApp.ts",
    ]
    misses: list[str] = []
    for path in mirror_files:
        if not path.exists():
            misses.append(f"missing file: {path}")
            continue
        text = path.read_text(encoding="utf-8")
        if expected_version not in text:
            misses.append(f"{path} does not contain {expected_version!r}")
    assert not misses, (
        f"Env-matrix version {expected_version!r} (from orchestration.md) "
        "not propagated to all mirrors:\n" + "\n".join(misses)
    )
