"""Tests for the --additive CLI flags on ``lia-graph-artifacts`` (Phase 6)."""

from __future__ import annotations

import io
import json
from contextlib import redirect_stdout

import pytest

from lia_graph.ingest import main, parser


# (a) parser exposes the four new flags.
def test_parser_exposes_additive_flags() -> None:
    p = parser()
    help_text = p.format_help()
    assert "--additive" in help_text
    assert "--delta-id" in help_text
    assert "--dry-run-delta" in help_text
    assert "--strict-parity" in help_text


# (b) parsing --additive + flags sets expected fields.
def test_parser_captures_additive_flag_values() -> None:
    p = parser()
    args = p.parse_args(
        [
            "--additive",
            "--delta-id",
            "delta_fixture_test",
            "--dry-run-delta",
            "--strict-parity",
            "--supabase-sink",
        ]
    )
    assert args.additive is True
    assert args.delta_id == "delta_fixture_test"
    assert args.dry_run_delta is True
    assert args.strict_parity is True
    assert args.supabase_sink is True


# (c) --additive without --supabase-sink errors with a clear message.
def test_additive_without_supabase_sink_errors() -> None:
    buf = io.StringIO()
    with redirect_stdout(buf):
        rc = main(
            [
                "--additive",
                "--no-supabase-sink",
                "--allow-non-local-env",
                "--json",
            ]
        )
    assert rc == 2
    payload = json.loads(buf.getvalue())
    assert payload["ok"] is False
    assert payload["error"] == "additive_requires_supabase"


# (d) --strict-parity flag defaults to False.
def test_strict_parity_defaults_false() -> None:
    p = parser()
    args = p.parse_args(["--additive"])
    assert args.strict_parity is False


# (e) --dry-run-delta flag defaults to False.
def test_dry_run_delta_defaults_false() -> None:
    p = parser()
    args = p.parse_args(["--additive"])
    assert args.dry_run_delta is False


# (f) --delta-id flag defaults to None (auto-generated by the runtime).
def test_delta_id_defaults_none() -> None:
    p = parser()
    args = p.parse_args(["--additive"])
    assert args.delta_id is None


# (g) env-matrix version string appears in all 5 mirror surfaces after Phase 6.
def test_env_matrix_version_landed_across_mirrors() -> None:
    """Phase 6 bumps the env matrix version to v2026-04-22-ac1 across:
    AGENTS.md, docs/guide/orchestration.md, docs/guide/env_guide.md,
    CLAUDE.md, frontend/src/features/orchestration/orchestrationApp.ts.
    """
    from pathlib import Path

    repo_root = Path(__file__).resolve().parent.parent
    expected_version = "v2026-04-22-ac1"
    expected_files = [
        repo_root / "AGENTS.md",
        repo_root / "docs" / "guide" / "orchestration.md",
        repo_root / "docs" / "guide" / "env_guide.md",
        repo_root / "CLAUDE.md",
        repo_root / "frontend" / "src" / "features" / "orchestration" / "orchestrationApp.ts",
    ]
    misses: list[str] = []
    for path in expected_files:
        if not path.exists():
            misses.append(f"missing file: {path}")
            continue
        text = path.read_text(encoding="utf-8")
        if expected_version not in text:
            misses.append(f"{path} does not contain {expected_version!r}")
    assert not misses, "Env-matrix version not fully propagated:\n" + "\n".join(misses)
